// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/notifications': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/notifications.get').default>>>>
    }
    '/api/admin/notifications/read-all': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/notifications/read-all.put').default>>>>
    }
    '/api/admin/notifications/read': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/notifications/read.put').default>>>>
    }
    '/api/admin/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/stats.get').default>>>>
    }
    '/api/admin/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/[id].put').default>>>>
    }
    '/api/admin/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/users/index.post').default>>>>
    }
    '/api/analytics/content': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analytics/content.get').default>>>>
    }
    '/api/analytics/dashboard': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analytics/dashboard.get').default>>>>
    }
    '/api/analytics/reports': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analytics/reports.get').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/bookings': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookings.post').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookings').default>>>>
    }
    '/api/bookings/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookings/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookings/[id].put').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/bookings/[id]').default>>>>
    }
    '/api/cms/editor': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cms/editor.post').default>>>>
    }
    '/api/cms/editor/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cms/editor/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cms/editor/[id].put').default>>>>
    }
    '/api/cms/navigation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cms/navigation.get').default>>>>
    }
    '/api/cms/pages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cms/pages.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cms/pages.post').default>>>>
    }
    '/api/cms/pages/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cms/pages/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cms/pages/[id].put').default>>>>
    }
    '/api/cms/pages/home': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cms/pages/home.get').default>>>>
    }
    '/api/cms/sections': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cms/sections.post').default>>>>
    }
    '/api/cms/sections/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cms/sections/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cms/sections/[id].put').default>>>>
    }
    '/api/cms/site-settings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cms/site-settings.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cms/site-settings.put').default>>>>
    }
    '/api/contact-messages': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contact-messages.post').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contact-messages').default>>>>
    }
    '/api/contact-messages/:id': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contact-messages/[id].put').default>>>>
    }
    '/api/contact-messages/mark-all-read': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contact-messages/mark-all-read.put').default>>>>
    }
    '/api/content': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content').default>>>>
    }
    '/api/content/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[id].delete').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/content/[id]').default>>>>
    }
    '/api/destination-contact-form': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/destination-contact-form').default>>>>
    }
    '/api/destinations': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/destinations.post').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/destinations').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/destinations/index.get').default>>>>
    }
    '/api/destinations/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/destinations/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/destinations/[id].put').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/destinations/[id]').default>>>>
    }
    '/api/destinations/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/destinations/import.post').default>>>>
    }
    '/api/images/delete': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images/delete.post').default>>>>
    }
    '/api/images/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images/list.get').default>>>>
    }
    '/api/images/test': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images/test.get').default>>>>
    }
    '/api/images/upload-destination': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images/upload-destination.post').default>>>>
    }
    '/api/images/upload-package': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images/upload-package.post').default>>>>
    }
    '/api/images/upload': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/images/upload.post').default>>>>
    }
    '/api/package-contact-form': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/package-contact-form').default>>>>
    }
    '/api/packages': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/packages.post').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/packages').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/packages/index.get').default>>>>
    }
    '/api/packages/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/packages/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/packages/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/packages/[id].put').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/packages/[id]').default>>>>
    }
    '/api/public/navigation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public/navigation.get').default>>>>
    }
    '/api/public/pages/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public/pages/[id].get').default>>>>
    }
    '/api/public/pages/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public/pages/[slug].get').default>>>>
    }
    '/api/public/pages/home': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public/pages/home.get').default>>>>
    }
    '/api/public/site-settings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/public/site-settings.get').default>>>>
    }
    '/api/seo': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/seo/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/seo/index.put').default>>>>
    }
    '/api/seo/pages/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/seo/pages/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/seo/pages/[id].put').default>>>>
    }
    '/api/seo/pages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/seo/pages/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/seo/pages/index.post').default>>>>
    }
    '/api/seo/sitemap/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/seo/sitemap/generate.post').default>>>>
    }
    '/api/settings': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/settings').default>>>>
    }
    '/api/sitemap.xml': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sitemap.xml.get').default>>>>
    }
    '/api/users': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users.post').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users').default>>>>
    }
    '/api/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].put').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]').default>>>>
    }
    '/sitemap_index.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-simple-sitemap/dist/runtime/routes/sitemap_index.xml').default>>>>
    }
    '/en-US-sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-simple-sitemap/dist/runtime/middleware/[sitemap]-sitemap.xml').default>>>>
    }
    '/ar-SA-sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-simple-sitemap/dist/runtime/middleware/[sitemap]-sitemap.xml').default>>>>
    }
    '/__sitemap__/style.xsl': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-simple-sitemap/dist/runtime/routes/sitemap.xsl').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-simple-sitemap/dist/runtime/routes/sitemap.xml').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}